import { type Form, FormStatus, FormType } from '@reki/domain';

export const defaultForms: Form[] = [
  {
    id: '085c59c7-4345-4aae-85fb-6a2d14f13acd',
    title: 'Осмотр инструктора-методиста ЛФК',
    type: FormType.LFK,
    status: FormStatus.ACTIVE,
    version: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    schema: {
      sections: [
        {
          title: 'Общая информация',
          fields: [
            {
              name: 'therapistName',
              type: 'text',
              label: 'ФИО специалиста',
              required: true,
            },
            {
              name: 'examinationDate',
              type: 'date',
              label: 'Дата осмотра',
              required: true,
            },
            {
              name: 'patientName',
              type: 'text',
              label: 'ФИО пациента',
              required: true,
            },
          ],
        },
        {
          title: 'Двигательные навыки',
          fields: [
            {
              name: 'headHolding',
              type: 'checkbox-group',
              label: 'Удержание головы',
              options: [
                'Удерживает',
                'Не удерживает',
                'Удерживает несколько минут',
                'С наклоном вправо',
                'С наклоном влево',
              ],
            },
            {
              name: 'turns',
              type: 'checkbox-group',
              label: 'Перевороты',
              options: [
                'Со спины на живот',
                'С живота на спину',
                'Блоком',
                'Вправо',
                'Влево',
              ],
            },
            {
              name: 'lyingOnStomach',
              type: 'checkbox-group',
              label: 'Лежа на животе',
              options: [
                'Опоры на руки нет',
                'Опирается на предплечья',
                'Опирается на выпрямленные руки',
                'Кисти сжаты в кулак',
                'D',
                'S',
              ],
            },
            {
              name: 'sittingOnHeels',
              type: 'checkbox-group',
              label: 'Переход в позу сидя на пятках',
              options: [
                'Отсутствует',
                'С помощью взрослого',
                'Сидит не долго',
                'С опорой на предплечья',
                'С опорой на выпрямленные руки',
                'Кисти сжаты в кулак',
                'D',
                'S',
              ],
            },
            {
              name: 'crawling',
              type: 'checkbox-group',
              label: 'Ползанье по-пластунски',
              options: [
                'Отсутствуют',
                'Согласованно',
                'Подтягиваясь на предплечьях',
                'Отталкиваясь ногами',
                'Реципрокно',
              ],
            },
            {
              name: 'standingOnAllFours',
              type: 'checkbox-group',
              label: 'Стояние на четвереньках',
              options: ['Отсутствует', 'Прыжками', 'Реципрокно'],
            },
            {
              name: 'kneelingTransition',
              type: 'checkbox-group',
              label: 'Переход в позу стоя на коленях',
              options: [
                'Отсутствует',
                'У опоры',
                'Самостоятельно',
                'Передвигается у опоры',
                'Передвигается самостоятельно',
              ],
            },
            {
              name: 'sittingTransition',
              type: 'checkbox-group',
              label: 'Переход в положение сидя',
              options: [
                'С опорой на правую руку',
                'С опорой на левую руку',
                'При фиксации ног',
                'С поворотом на бок',
                'D',
                'S',
                'С поворотом на живот',
              ],
            },
            {
              name: 'sitting',
              type: 'checkbox-group',
              label: 'Сидит',
              options: [
                'Не сидит',
                'По-турецки',
                'С прямыми ногами',
                'С опущенными ногами',
                'С опорой на руки',
                'D',
                'S',
                'Самостоятельно',
                'С помощью взрослого',
              ],
            },
            {
              name: 'standing',
              type: 'checkbox-group',
              label: 'Стоит',
              options: [
                'Не стоит',
                'У опоры',
                'С поддержкой за 1 руку',
                'Несколько секунд',
                'Несколько минут',
                'Долго',
              ],
            },
            {
              name: 'walking',
              type: 'checkbox-group',
              label: 'Ходит',
              options: [
                'Не ходит',
                'Ходит',
                'С поддержкой со стороны спины',
                'С поддержкой за 1 руку',
                'D',
                'S',
                'Самостоятельно',
                'Устойчиво',
                'Неустойчиво',
                'Стремительно',
                'С ортопедической обувью',
                'Без обуви',
                'Передвигается в ходунках',
                'С колесами спереди',
                'С поддержкой типа трусики',
                'С поддержкой сбоку и сзади',
                'С четырехопорной тростью',
                'С тростью',
                'С канадскими палочками',
                'Передвигается на расстояние 5 метров',
                '10 метров',
                '25 метров',
                '50 метров',
                'Более 50 метров',
              ],
            },
          ],
        },
        {
          title: 'Походка',
          fields: [
            {
              name: 'spine',
              type: 'checkbox-group',
              label: 'Спина',
              options: [
                'Гиперкифоз',
                'Гиперлордоз',
                'Круглая спина',
                'Кругло-вогнутая спина',
                'С-образное искривление позвоночника',
                'Вправо',
                'Влево',
                'S-образное искривление позвоночника',
                'Нарушение осанки',
                'Ослаблены мышцы туловища в шейном отделе позвоночника',
                'D',
                'S',
                'Ослаблены мышцы туловища в грудном отделе позвоночника',
                'D',
                'S',
                'Ослаблены мышцы туловища в поясничном отделе позвоночника',
                'D',
                'S',
                'Ослаблены мышцы брюшного пресса',
                'D',
                'S',
                'Ослаблены ягодичные мышцы',
                'D',
                'S',
                'Фронтальные колебания туловища',
                'Сагиттальные колебания туловища',
                'Фронтальные колебания таза',
                'Руки в сгибательно-пронаторном положении',
                'D',
                'S',
                'Кисти сжаты в кулак',
                'D',
                'S',
                'Ротация бедер внутрь',
                'D',
                'S',
                'Разгибание в коленном суставе затруднено',
                'D',
                'S',
                'Отсутствует',
                'D',
                'S',
                'Перекрест на уровне бедер',
                'Перекрест на уровне колен',
                'Перекрест на уровне нижней трети голени',
                'Перекрест на уровне стоп',
              ],
            },
            {
              name: 'lowerLimbAlignment',
              type: 'checkbox-group',
              label: 'Установка нижних конечностей',
              options: [
                'Х-образная',
                'О-образная',
                'Рекурвация в коленных суставах',
                'D',
                'S',
              ],
            },
            {
              name: 'footAlignment',
              type: 'checkbox-group',
              label: 'Установка стоп',
              options: [
                'Плоско',
                'Вальгус',
                'Варус',
                'D',
                'S',
                'Эквино',
                'Вальгус',
                'Варус',
                'D',
                'S',
                'Высокий эквинус',
                'D',
                'S',
                'Загребает передним отделом стоп',
                'D',
                'S',
                'С приведением переднего отдела стопы внутрь',
                'D',
                'S',
                'С отведением переднего отдела стопы наружу',
                'D',
                'S',
              ],
            },
          ],
        },
        {
          title: 'Наличие контрактур в суставах',
          fields: [
            {
              name: 'wristContractures',
              type: 'checkbox-group',
              label: 'Лучезапястном',
              options: [
                'Сгибательная',
                'D',
                'S',
                'Разгибательная',
                'D',
                'S',
                'Динамическая',
                'Фиксированная',
              ],
            },
            {
              name: 'elbowContractures',
              type: 'checkbox-group',
              label: 'Локтевом',
              options: [
                'Сгибательная',
                'D',
                'S',
                'Пронаторная',
                'D',
                'S',
                'Динамическая',
                'Фиксированная',
              ],
            },
            {
              name: 'shoulderContractures',
              type: 'checkbox-group',
              label: 'Плечевом',
              options: [
                'Сгибательная',
                'D',
                'S',
                'Разгибательная',
                'D',
                'S',
                'Пронаторная',
                'D',
                'S',
                'Динамическая',
                'Фиксированная',
              ],
            },
            {
              name: 'ankleContractures',
              type: 'checkbox-group',
              label: 'Голеностопном',
              options: [
                'Сгибательная',
                'D',
                'S',
                'Разгибательная',
                'D',
                'S',
                'Динамическая',
                'Фиксированная',
              ],
            },
            {
              name: 'kneeContractures',
              type: 'checkbox-group',
              label: 'Коленном',
              options: [
                'Сгибательная',
                'D',
                'S',
                'Динамическая',
                'Фиксированная',
              ],
            },
            {
              name: 'hipContractures',
              type: 'checkbox-group',
              label: 'Тазобедренном',
              options: [
                'Сгибательная',
                'D',
                'S',
                'Приводящая',
                'D',
                'S',
                'Отводящая',
                'D',
                'S',
                'Динамическая',
                'Фиксированная',
              ],
            },
          ],
        },
        {
          title: 'Наличие нестабильности в суставах',
          fields: [
            {
              name: 'jointInstability',
              type: 'checkbox-group',
              label: 'Наличие нестабильности в суставах',
              options: [
                'Лучезапястном',
                'D',
                'S',
                'Локтевом',
                'D',
                'S',
                'Плечевом',
                'D',
                'S',
                'Голеностопном',
                'D',
                'S',
                'Коленном',
                'D',
                'S',
                'Тазобедренном',
                'D',
                'S',
              ],
            },
          ],
        },
        {
          title: 'Наличие патологических рефлексов новорожденных',
          fields: [
            {
              name: 'pathologicalReflexes',
              type: 'checkbox-group',
              label: 'Наличие патологических рефлексов новорожденных',
              options: ['ААСШТР', 'СШТР', 'ЛТР'],
            },
          ],
        },
        {
          title: 'Измерение объема движений по суставам нижних конечностей',
          fields: [
            {
              name: 'rectusMeasurement',
              type: 'number',
              label: 'Ректус (градусы)',
              min: 0,
              max: 180,
            },
            {
              name: 'externalHipRotation',
              type: 'number',
              label: 'Наружная ротация бедра (градусы)',
              min: 0,
              max: 90,
            },
            {
              name: 'hamstringMeasurement',
              type: 'number',
              label: 'Хамстринг (градусы)',
              min: 0,
              max: 180,
            },
            {
              name: 'hipFlexion',
              type: 'number',
              label: 'Тазобедренный сустав - сгибание (градусы)',
              min: 0,
              max: 120,
            },
            {
              name: 'hipExtension',
              type: 'number',
              label: 'Тазобедренный сустав - разгибание (градусы)',
              min: 0,
              max: 30,
            },
            {
              name: 'hipAbduction',
              type: 'number',
              label: 'Тазобедренный сустав - отведение (градусы)',
              min: 0,
              max: 45,
            },
            {
              name: 'kneeFlexion',
              type: 'number',
              label: 'Коленный сустав - сгибание (градусы)',
              min: 0,
              max: 135,
            },
            {
              name: 'kneeExtension',
              type: 'number',
              label: 'Коленный сустав - разгибание (градусы)',
              min: 0,
              max: 10,
            },
            {
              name: 'ankleDorsiflexion',
              type: 'number',
              label: 'Голеностопный сустав - тыльное сгибание (градусы)',
              min: 0,
              max: 20,
            },
            {
              name: 'anklePlantarflexion',
              type: 'number',
              label: 'Голеностопный сустав - разгибание (градусы)',
              min: 0,
              max: 50,
            },
          ],
        },
        {
          title: 'Лечебная гимнастика направлена на',
          fields: [
            {
              name: 'therapeuticGoals',
              type: 'checkbox-group',
              label: 'Лечебная гимнастика направлена на:',
              options: [
                'Глазодвигательное стимулирование',
                'Лечение положением',
                'Диагональная гимнастика',
                'Занятия в вертикализаторе',
                'Упражнения для верхних конечностей по методике Мишель ля Матье',
                'Развитие отведения пальца кисти',
                'Экстензии кисти',
                'Супинации предплечий',
                'Разгибания в локтевых суставах',
                'Отведения в плечевых суставах',
                'Стабилизация лопаток',
                'Гимнастика по методике «Баланс»',
                'Упражнения на координацию и равновесие',
                'Формирование правильного кинематического шага: Сгибание',
                'Вынос бедра',
                'Разгибание голени',
                'Тыльное сгибание стопы',
                'Постановка стопы на пятку',
                'Перекат с пятки на носок',
                'Передний толчок',
              ],
            },
          ],
        },
        {
          title: 'Коррекция двигательных навыков',
          fields: [
            {
              name: 'headHoldingCorrection',
              type: 'checkbox-group',
              label: 'Удержание головы',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'forearmSupportCorrection',
              type: 'checkbox-group',
              label: 'Опора на предплечья',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'straightArmSupportCorrection',
              type: 'checkbox-group',
              label: 'Опора на выпрямленные руки',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'backToStomachTurnCorrection',
              type: 'checkbox-group',
              label: 'Переворот со спины на живот',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'stomachToBackTurnCorrection',
              type: 'checkbox-group',
              label: 'Переворот с живота на спину',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'sittingTransitionCorrection',
              type: 'checkbox-group',
              label: 'Переход в положение сидя',
              options: [
                'Через правую руку',
                'Через левую руку',
                'Без помощи рук',
              ],
            },
            {
              name: 'crawlingCorrection',
              type: 'checkbox-group',
              label: 'Ползание по-пластунски',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'allFoursCrawlingCorrection',
              type: 'checkbox-group',
              label: 'Ползание на четвереньках',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'kneelingMovementCorrection',
              type: 'checkbox-group',
              label: 'Передвижение стоя на коленях',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'kneelingStandingCorrection',
              type: 'checkbox-group',
              label: 'Вставание с колен',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'walkerWalkingCorrection',
              type: 'checkbox-group',
              label: 'Ходьба с ходунками',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'crutchWalkingCorrection',
              type: 'checkbox-group',
              label: 'Ходьба с канадскими палочками',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'caneWalkingCorrection',
              type: 'checkbox-group',
              label: 'Ходьба с тростью',
              options: ['Развитие', 'Улучшение'],
            },
            {
              name: 'wheelchairTraining',
              type: 'checkbox',
              label: 'Обучение передвижению на коляске',
            },
          ],
        },
        {
          title: 'Укрепление мышц',
          fields: [
            {
              name: 'muscleStrengthening',
              type: 'checkbox-group',
              label: 'Укрепление мышц',
              options: [
                'Спины',
                'Брюшного пресса',
                'Косых мышц живота',
                'D',
                'S',
                'Ягодичных',
                'Разгибателей предплечий',
                'Супинаторов предплечий',
                'D',
                'S',
                'Экстензоров кисти',
                'D',
                'S',
                'Отводящих бедер',
                'D',
                'S',
                'Разгибателей голени',
                'D',
                'S',
                'Тыльного сгибания стопы',
                'D',
                'S',
                'Икроножных мышц',
                'D',
                'S',
              ],
            },
          ],
        },
        {
          title: 'Расслабление, растягивание мышц',
          fields: [
            {
              name: 'muscleRelaxation',
              type: 'checkbox-group',
              label: 'Расслабление, растягивание мышц',
              options: [
                'Больших грудных мышц',
                'D',
                'S',
                'Косых мышц живота',
                'D',
                'S',
                'Сгибателей предплечий',
                'D',
                'S',
                'Пронаторов предплечий',
                'D',
                'S',
                'Флексирующих кисть',
                'D',
                'S',
                'Сгибателей бедра',
                'D',
                'S',
                'Сгибателей голени',
                'D',
                'S',
                'Икроножных мышц',
                'D',
                'S',
                'Ахиллова сухожилия',
                'D',
                'S',
              ],
            },
          ],
        },
        {
          title: 'Коррекция установок, контрактур и деформаций',
          fields: [
            {
              name: 'postureCorrection',
              type: 'checkbox-group',
              label: 'Коррекция установок, контрактур и деформаций',
              options: [
                'Х-образной установки нижних конечностей',
                'О-образной установки нижних конечностей',
                'Рекурвации',
                'Плоско-вальгусной установки стоп',
                'Плоско-варусной установки стоп',
                'Эквино-варусной установки стоп',
                'Эквинуса',
              ],
            },
            {
              name: 'orthopedicDevices',
              type: 'checkbox-group',
              label: 'Ортопедические устройства',
              options: [
                'Вертикализация на всю ногу на две ноги с полукорсетом',
                'Стоять, ходить в туторах на коленные суставы+аппараты на голеностопные суставы (ортопедическая обувь)+реклинирующая система',
                'Использование динамического корригирующего устройства',
              ],
            },
          ],
        },
        {
          title: 'Дополнительные упражнения',
          fields: [
            {
              name: 'passiveRangeIncrease',
              type: 'checkbox',
              label: 'Увеличение пассивного объема движений в суставах',
            },
            {
              name: 'generalExercises',
              type: 'checkbox',
              label: 'Общеразвивающие упражнения',
            },
            {
              name: 'jumpingDevelopment',
              type: 'checkbox-group',
              label: 'Развитие прыжков',
              options: ['На правой ноге', 'На левой ноге', 'На двух ногах'],
            },
          ],
        },
        {
          title: 'Заключение',
          fields: [
            {
              name: 'conclusion',
              type: 'textarea',
              label: 'Заключение',
              required: true,
            },
            {
              name: 'recommendations',
              type: 'textarea',
              label: 'Рекомендации',
              required: true,
            },
          ],
        },
      ],
    },
  },
  {
    id: 'b5340efc-e968-4112-a847-c84735ec32ef',
    title: 'FIM — мера функциональной независимости',
    type: FormType.FIM,
    status: FormStatus.ACTIVE,
    version: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    schema: {
      sections: [
        {
          title: 'Информация о тесте',
          fields: [
            {
              name: 'therapistName',
              type: 'text',
              label: 'ФИО специалиста',
              required: true,
            },
            {
              name: 'examinationDate',
              type: 'date',
              label: 'Дата проведения',
              required: true,
            },
            {
              name: 'patientName',
              type: 'text',
              label: 'ФИО пациента',
              required: true,
            },
          ],
        },
        {
          title: 'Самообслуживание (ADL)',
          fields: [
            {
              name: 'eatingScoreBefore',
              type: 'rating',
              label: 'Прием пищи (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'eatingScoreAfter',
              type: 'rating',
              label: 'Прием пищи (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'swallowingScoreBefore',
              type: 'rating',
              label: 'Глотание (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'swallowingScoreAfter',
              type: 'rating',
              label: 'Глотание (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'groomingScoreBefore',
              type: 'rating',
              label: 'Уход за собой (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'groomingScoreAfter',
              type: 'rating',
              label: 'Уход за собой (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'bathingScoreBefore',
              type: 'rating',
              label: 'Купание (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'bathingScoreAfter',
              type: 'rating',
              label: 'Купание (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'dressUpperScoreBefore',
              type: 'rating',
              label: 'Одевание верхней части (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'dressUpperScoreAfter',
              type: 'rating',
              label: 'Одевание верхней части (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'dressLowerScoreBefore',
              type: 'rating',
              label: 'Одевание нижней части (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'dressLowerScoreAfter',
              type: 'rating',
              label: 'Одевание нижней части (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'toiletingScoreBefore',
              type: 'rating',
              label: 'Туалет (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'toiletingScoreAfter',
              type: 'rating',
              label: 'Туалет (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'bladderScoreBefore',
              type: 'rating',
              label: 'Контроль мочеиспускания (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'bladderScoreAfter',
              type: 'rating',
              label: 'Контроль мочеиспускания (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'bowelScoreBefore',
              type: 'rating',
              label: 'Контроль дефекации (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'bowelScoreAfter',
              type: 'rating',
              label: 'Контроль дефекации (После)',
              min: 1,
              max: 7,
            },
          ],
        },
        {
          title: 'Перемещения и мобильность',
          fields: [
            {
              name: 'bedTransferScoreBefore',
              type: 'rating',
              label: 'Перемещение кровать/стул/коляска (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'bedTransferScoreAfter',
              type: 'rating',
              label: 'Перемещение кровать/стул/коляска (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'toiletTransferScoreBefore',
              type: 'rating',
              label: 'Перемещение туалет (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'toiletTransferScoreAfter',
              type: 'rating',
              label: 'Перемещение туалет (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'bathTransferScoreBefore',
              type: 'rating',
              label: 'Перемещение ванна/душ (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'bathTransferScoreAfter',
              type: 'rating',
              label: 'Перемещение ванна/душ (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'carTransferScoreBefore',
              type: 'rating',
              label: 'Перемещение автомобиль (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'carTransferScoreAfter',
              type: 'rating',
              label: 'Перемещение автомобиль (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'locomotionScoreBefore',
              type: 'rating',
              label: 'Передвижение (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'locomotionScoreAfter',
              type: 'rating',
              label: 'Передвижение (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'stairsScoreBefore',
              type: 'rating',
              label: 'Подъем по лестнице (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'stairsScoreAfter',
              type: 'rating',
              label: 'Подъем по лестнице (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'mobilityScoreBefore',
              type: 'rating',
              label: 'Мобильность (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'mobilityScoreAfter',
              type: 'rating',
              label: 'Мобильность (После)',
              min: 1,
              max: 7,
            },
          ],
        },
        {
          title: 'Коммуникация и когнитивные/социальные навыки',
          fields: [
            {
              name: 'comprehensionScoreBefore',
              type: 'rating',
              label: 'Понимание (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'comprehensionScoreAfter',
              type: 'rating',
              label: 'Понимание (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'expressionScoreBefore',
              type: 'rating',
              label: 'Выражение (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'expressionScoreAfter',
              type: 'rating',
              label: 'Выражение (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'readingScoreBefore',
              type: 'rating',
              label: 'Чтение (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'readingScoreAfter',
              type: 'rating',
              label: 'Чтение (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'writingScoreBefore',
              type: 'rating',
              label: 'Письмо (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'writingScoreAfter',
              type: 'rating',
              label: 'Письмо (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'speechScoreBefore',
              type: 'rating',
              label: 'Речь (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'speechScoreAfter',
              type: 'rating',
              label: 'Речь (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'socialInteractionScoreBefore',
              type: 'rating',
              label: 'Социальное взаимодействие (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'socialInteractionScoreAfter',
              type: 'rating',
              label: 'Социальное взаимодействие (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'emotionalStatusScoreBefore',
              type: 'rating',
              label: 'Эмоциональное состояние (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'emotionalStatusScoreAfter',
              type: 'rating',
              label: 'Эмоциональное состояние (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'adjustmentScoreBefore',
              type: 'rating',
              label: 'Адаптация (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'adjustmentScoreAfter',
              type: 'rating',
              label: 'Адаптация (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'leisureActivitiesScoreBefore',
              type: 'rating',
              label: 'Досуговые занятия (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'leisureActivitiesScoreAfter',
              type: 'rating',
              label: 'Досуговые занятия (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'problemSolvingScoreBefore',
              type: 'rating',
              label: 'Решение проблем (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'problemSolvingScoreAfter',
              type: 'rating',
              label: 'Решение проблем (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'memoryScoreBefore',
              type: 'rating',
              label: 'Память (До)',
              min: 1,
              max: 7,
            },
            {
              name: 'memoryScoreAfter',
              type: 'rating',
              label: 'Память (После)',
              min: 1,
              max: 7,
            },
            {
              name: 'orientation',
              type: 'checkbox-group',
              label: 'Ориентация',
              options: ['До', 'После'],
            },
            {
              name: 'orientationScore',
              type: 'rating',
              label: 'Оценка ориентации',
              min: 1,
              max: 7,
            },
            {
              name: 'concentration',
              type: 'checkbox-group',
              label: 'Концентрация',
              options: ['До', 'После'],
            },
            {
              name: 'concentrationScore',
              type: 'rating',
              label: 'Оценка концентрации',
              min: 1,
              max: 7,
            },
            {
              name: 'safetyAwareness',
              type: 'checkbox-group',
              label: 'Осведомленность о безопасности',
              options: ['До', 'После'],
            },
            {
              name: 'safetyAwarenessScore',
              type: 'rating',
              label: 'Оценка осведомленности о безопасности',
              min: 1,
              max: 7,
            },
          ],
        },
        {
          title: 'Заключение',
          fields: [
            {
              name: 'totalScore',
              type: 'number',
              label: 'Общий балл',
              readOnly: true,
            },
            {
              name: 'conclusion',
              type: 'textarea',
              label: 'Заключение',
              required: true,
            },
            {
              name: 'recommendations',
              type: 'textarea',
              label: 'Рекомендации',
              required: true,
            },
          ],
        },
      ],
    },
  },
];
