import { FormEntryStatus } from '@reki/domain';

export const mockFormEntries = [
  {
    id: 'mock-entry-1',
    formId: '36541e76-d3cf-4618-93f2-b63f36f28660', // FIM форма
    patientId: '1a27c06b-a2fc-471b-9057-a369d0e669d0',
    status: FormEntryStatus.COMPLETED,
    data: {
      therapistName: 'Иванова Анна Петровна',
      examinationDate: '2025-09-01',
      // Самообслуживание (ADL)
      eatingScoreBefore: 4,
      eatingScoreAfter: 6,
      swallowingScoreBefore: 5,
      swallowingScoreAfter: 7,
      groomingScoreBefore: 3,
      groomingScoreAfter: 5,
      bathingScoreBefore: 2,
      bathingScoreAfter: 4,
      dressUpperScoreBefore: 4,
      dressUpperScoreAfter: 6,
      dressLowerScoreBefore: 3,
      dressLowerScoreAfter: 5,
      toiletingScoreBefore: 4,
      toiletingScoreAfter: 6,
      bladderScoreBefore: 5,
      bladderScoreAfter: 6,
      bowelScoreBefore: 4,
      bowelScoreAfter: 5,
      // Перемещения и мобильность
      bedTransferScoreBefore: 3,
      bedTransferScoreAfter: 5,
      toiletTransferScoreBefore: 2,
      toiletTransferScoreAfter: 4,
      bathTransferScoreBefore: 1,
      bathTransferScoreAfter: 3,
      carTransferScoreBefore: 2,
      carTransferScoreAfter: 4,
      locomotionScoreBefore: 2,
      locomotionScoreAfter: 4,
      stairsScoreBefore: 1,
      stairsScoreAfter: 3,
      mobilityScoreBefore: 2,
      mobilityScoreAfter: 4,
      // Коммуникация и когнитивные навыки
      comprehensionScoreBefore: 6,
      comprehensionScoreAfter: 7,
      expressionScoreBefore: 5,
      expressionScoreAfter: 6,
      readingScoreBefore: 5,
      readingScoreAfter: 6,
      writingScoreBefore: 4,
      writingScoreAfter: 5,
      speechScoreBefore: 5,
      speechScoreAfter: 6,
      socialInteractionScoreBefore: 5,
      socialInteractionScoreAfter: 6,
      emotionalStatusScoreBefore: 4,
      emotionalStatusScoreAfter: 5,
      adjustmentScoreBefore: 4,
      adjustmentScoreAfter: 5,
      leisureActivitiesScoreBefore: 3,
      leisureActivitiesScoreAfter: 4,
      problemSolvingScoreBefore: 4,
      problemSolvingScoreAfter: 5,
      memoryScoreBefore: 5,
      memoryScoreAfter: 6,
      orientationScoreBefore: 5,
      orientationScoreAfter: 6,
      concentrationScoreBefore: 4,
      concentrationScoreAfter: 5,
      safetyAwarenessScoreBefore: 4,
      safetyAwarenessScoreAfter: 5,
      conclusion:
        'Пациент демонстрирует значительное улучшение функциональной независимости',
      recommendations:
        'Продолжить реабилитационные мероприятия, уделить внимание координации движений',
    },
    score: 95,
    completedAt: '2025-09-01T10:30:00.000Z',
    createdAt: '2025-09-01T09:00:00.000Z',
    updatedAt: '2025-09-01T10:30:00.000Z',
  },
  {
    id: 'mock-entry-2',
    formId: '1652b729-e2ec-4cd4-9489-d9ab38e16db8', // ЛФК форма
    patientId: 'c9cd7f5f-90cd-4b75-9996-94bc7dc9e211',
    status: FormEntryStatus.COMPLETED,
    data: {
      therapistName: 'Петров Сергей Александрович',
      examinationDate: '2025-09-01',
      diagnosis: 'Состояние после инсульта',
      complaints: 'Слабость в правой руке, нарушение координации',
      anamnesis: 'Инсульт 3 месяца назад, гемипарез справа',
      generalCondition: 'Удовлетворительное',
      consciousness: 'Ясное',
      position: 'Активное',
      mobility: 'С помощью вспомогательных средств',
      muscleStrength: 3,
      jointMobility: 4,
      balance: 2,
      coordination: 2,
      conclusion: 'Умеренные нарушения двигательных функций',
      recommendations: 'Индивидуальная программа ЛФК, тренировка равновесия',
    },
    score: 65,
    completedAt: '2025-09-01T14:15:00.000Z',
    createdAt: '2025-09-01T13:00:00.000Z',
    updatedAt: '2025-09-01T14:15:00.000Z',
  },
  {
    id: 'mock-entry-3',
    formId: '36541e76-d3cf-4618-93f2-b63f36f28660', // FIM форма
    patientId: '3c0298d1-3ef2-4623-a963-7005274afbbb',
    status: FormEntryStatus.IN_PROGRESS,
    data: {
      therapistName: 'Сидорова Мария Владимировна',
      examinationDate: '2025-09-01',
      eating: ['До'],
      eatingScore: 4,
      swallowing: ['До'],
      swallowingScore: 5,
      grooming: ['До'],
      groomingScore: 3,
      bathing: ['До'],
      bathingScore: 2,
      dressUpper: ['До'],
      dressUpperScore: 3,
      dressLower: ['До'],
      dressLowerScore: 2,
      toileting: ['До'],
      toiletingScore: 3,
      bladder: ['До'],
      bladderScore: 4,
      bowel: ['До'],
      bowelScore: 3,
      bedTransfer: ['До'],
      bedTransferScore: 2,
      toiletTransfer: ['До'],
      toiletTransferScore: 2,
      bathTransfer: ['До'],
      bathTransferScore: 1,
      carTransfer: ['До'],
      carTransferScore: 2,
      locomotion: ['До'],
      locomotionScore: 1,
      stairs: ['До'],
      stairsScore: 1,
      mobility: ['До'],
      mobilityScore: 1,
      comprehension: ['До'],
      comprehensionScore: 5,
      expression: ['До'],
      expressionScore: 4,
      reading: ['До'],
      readingScore: 4,
      writing: ['До'],
      writingScore: 3,
      speech: ['До'],
      speechScore: 4,
      socialInteraction: ['До'],
      socialInteractionScore: 4,
      emotionalStatus: ['До'],
      emotionalStatusScore: 3,
      adjustment: ['До'],
      adjustmentScore: 3,
      leisureActivities: ['До'],
      leisureActivitiesScore: 2,
      problemSolving: ['До'],
      problemSolvingScore: 3,
      memory: ['До'],
      memoryScore: 4,
      orientation: ['До'],
      orientationScore: 4,
      concentration: ['До'],
      concentrationScore: 3,
      safetyAwareness: ['До'],
      safetyAwarenessScore: 3,
    },
    createdAt: '2025-09-01T16:00:00.000Z',
    updatedAt: '2025-09-01T16:00:00.000Z',
  },
  {
    id: 'mock-entry-4',
    formId: '1652b729-e2ec-4cd4-9489-d9ab38e16db8', // ЛФК форма
    patientId: '3dd12685-f1f2-4e7c-97e9-0128f64ab87f',
    status: FormEntryStatus.IN_PROGRESS,
    data: {
      therapistName: 'Козлов Дмитрий Игоревич',
      examinationDate: '2025-09-01',
      diagnosis: 'Остеохондроз поясничного отдела',
      complaints: 'Боль в пояснице, иррадиация в ногу',
      anamnesis: 'Хроническая боль в спине 2 года',
      generalCondition: 'Удовлетворительное',
      consciousness: 'Ясное',
      position: 'Активное',
      mobility: 'Самостоятельно',
      muscleStrength: 4,
      jointMobility: 3,
      balance: 4,
      coordination: 4,
    },
    createdAt: '2025-09-01T11:30:00.000Z',
    updatedAt: '2025-09-01T11:30:00.000Z',
  },
  {
    id: 'mock-entry-5',
    formId: '36541e76-d3cf-4618-93f2-b63f36f28660', // FIM форма
    patientId: '0d776fd7-bea2-41ef-b9d0-706dd8024cd6',
    status: FormEntryStatus.CANCELLED,
    data: {},
    createdAt: '2025-09-01T08:00:00.000Z',
    updatedAt: '2025-09-01T08:30:00.000Z',
  },
];
